[package]
name = "bun"
version = "0.1.0"
authors = ["Berk Çebi <berkcebi@gmail.com>"]
edition = "2021"

[dependencies]
bevy = "^0.7"
bevy_rapier2d = { version = "^0.14", features = ["simd-stable"] }
rand = "^0.8"
